apiVersion: v2
name: podinfo
description: Wrapper chart for podinfo (podinfo 6.15.0)
type: application
version: 0.3.1
appVersion: "6.15.0"
dependencies:
  - name: podinfo
    version: 6.15.0
    repository: https://stefanprodan.github.io/podinfo
